[project]
name = "trafficproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "EthanLin", email = "eason.lin@ascentis.com.sg" }
]
requires-python = ">=3.13"
dependencies = [
    "confluent-kafka>=2.15.0",
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.11.1",
    "pandas>=3.0.5",
    "pyarrow>=25.0.0",
    "pymongo>=4.17.0",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
]

[project.scripts]
trafficproject = "trafficproject:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
